INTEGER(KIND = 4), PARAMETER:: fftw_r2hc = 0
INTEGER(KIND = 4), PARAMETER:: fftw_hc2r = 1
INTEGER(KIND = 4), PARAMETER:: fftw_dht = 2
INTEGER(KIND = 4), PARAMETER:: fftw_redft00 = 3
INTEGER(KIND = 4), PARAMETER:: fftw_redft01 = 4
INTEGER(KIND = 4), PARAMETER:: fftw_redft10 = 5
INTEGER(KIND = 4), PARAMETER:: fftw_redft11 = 6
INTEGER(KIND = 4), PARAMETER:: fftw_rodft00 = 7
INTEGER(KIND = 4), PARAMETER:: fftw_rodft01 = 8
INTEGER(KIND = 4), PARAMETER:: fftw_rodft10 = 9
INTEGER(KIND = 4), PARAMETER:: fftw_rodft11 = 10
INTEGER(KIND = 4), PARAMETER:: fftw_forward = -1
INTEGER(KIND = 4), PARAMETER:: fftw_backward = +1
INTEGER(KIND = 4), PARAMETER:: fftw_measure = 0
INTEGER(KIND = 4), PARAMETER:: fftw_destroy_input = 1
INTEGER(KIND = 4), PARAMETER:: fftw_unaligned = 2
INTEGER(KIND = 4), PARAMETER:: fftw_conserve_memory = 4
INTEGER(KIND = 4), PARAMETER:: fftw_exhaustive = 8
INTEGER(KIND = 4), PARAMETER:: fftw_preserve_input = 16
INTEGER(KIND = 4), PARAMETER:: fftw_patient = 32
INTEGER(KIND = 4), PARAMETER:: fftw_estimate = 64
INTEGER(KIND = 4), PARAMETER:: fftw_estimate_patient = 128
INTEGER(KIND = 4), PARAMETER:: fftw_believe_pcost = 256
INTEGER(KIND = 4), PARAMETER:: fftw_dft_r2hc_icky = 512
INTEGER(KIND = 4), PARAMETER:: fftw_nonthreaded_icky = 1024
INTEGER(KIND = 4), PARAMETER:: fftw_no_buffering = 2048
INTEGER(KIND = 4), PARAMETER:: fftw_no_indirect_op = 4096
INTEGER(KIND = 4), PARAMETER:: fftw_allow_large_generic = 8192
INTEGER(KIND = 4), PARAMETER:: fftw_no_rank_splits = 16384
INTEGER(KIND = 4), PARAMETER:: fftw_no_vrank_splits = 32768
INTEGER(KIND = 4), PARAMETER:: fftw_no_vrecurse = 65536
INTEGER(KIND = 4), PARAMETER:: fftw_no_simd = 131072
